"""
Report generation.
Queries pipeline results and generates a markdown summary.
Includes an optional LLM enhancement stub.
"""

from pathlib import Path
from datetime import datetime

import psycopg


def generate_report(conn: psycopg.Connection, quarantine_dir: str, output_path: str = "REPORT.md") -> None:
    """Generate a markdown report of pipeline results and data quality findings."""

    sections = []

    # Header
    sections.append("# Pipeline Report")
    sections.append(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}\n")

    # --- Section 1: Daily Metrics ---
    sections.append("## Daily Order Metrics\n")
    sections.append("| Date | Orders | Revenue | Avg Order Value |")
    sections.append("|------|--------|---------|-----------------|")

    with conn.cursor() as cur:
        cur.execute("SELECT * FROM v_daily_metrics ORDER BY order_date;")
        rows = cur.fetchall()
        for row in rows:
            sections.append(f"| {row[0]} | {row[1]} | {row[2]} | {row[3]} |")

    # --- Section 2: Top Customers ---
    sections.append("\n## Top Customers by Lifetime Spend\n")
    sections.append("| Rank | Customer | Email | Orders | Spend |")
    sections.append("|------|----------|-------|--------|-------|")

    with conn.cursor() as cur:
        cur.execute("SELECT * FROM v_top_customers_by_spend;")
        rows = cur.fetchall()
        for row in rows:
            sections.append(f"| {row[0]} | {row[2]} | {row[3]} | {row[4]} | {row[5]} |")

    # --- Section 3: Top SKUs ---
    sections.append("\n## Top SKUs by Revenue\n")
    sections.append("| Rank | SKU | Category | Units Sold | Revenue |")
    sections.append("|------|-----|----------|------------|---------|")

    with conn.cursor() as cur:
        cur.execute("SELECT * FROM v_top_skus;")
        rows = cur.fetchall()
        for row in rows:
            sections.append(f"| {row[0]} | {row[1]} | {row[2]} | {row[3]} | {row[4]} |")

    # --- Section 4: Data Quality Summary ---
    sections.append("\n## Data Quality Findings\n")

    # Read quarantine files
    quarantine_path = Path(quarantine_dir)
    for filename in ["customers.csv", "orders.csv", "order_items.csv"]:
        filepath = quarantine_path / filename
        if filepath.exists():
            import pandas as pd
            qdf = pd.read_csv(filepath)
            table_name = filename.replace(".csv", "")
            sections.append(f"### Quarantined: {table_name}\n")
            sections.append(f"**{len(qdf)} rows rejected:**\n")

            if "_rejection_reason" in qdf.columns:
                reason_counts = qdf["_rejection_reason"].value_counts()
                for reason, count in reason_counts.items():
                    sections.append(f"- `{reason}`: {count} row(s)")

            sections.append("")

    # --- Section 5: LLM Enhancement Stub ---
    sections.append("\n## Agentic Summary (Stub)\n")
    sections.append(
        "In production, this section would be generated by an LLM agent that:\n"
    )
    sections.append("1. Receives the metrics and quality findings above as context")
    sections.append("2. Generates a natural-language executive summary")
    sections.append("3. Highlights anomalies and recommends actions\n")
    sections.append("### How It Would Work\n")
    sections.append("```python")
    sections.append("import openai")
    sections.append("")
    sections.append("def generate_llm_summary(metrics: dict) -> str:")
    sections.append('    """Call an LLM to generate an executive summary."""')
    sections.append("")
    sections.append("    prompt = f\"\"\"")
    sections.append("    You are a data quality analyst. Given these pipeline metrics:")
    sections.append("    {metrics}")
    sections.append("")
    sections.append("    Write a brief executive summary highlighting:")
    sections.append("    - Overall data quality health")
    sections.append("    - Key revenue insights")
    sections.append("    - Anomalies or concerns")
    sections.append("    - Recommended actions")
    sections.append('    """')
    sections.append("")
    sections.append("    response = openai.ChatCompletion.create(")
    sections.append('        model="gpt-4",')
    sections.append("        messages=[")
    sections.append('            {"role": "system", "content": "You are a data quality analyst."},')
    sections.append('            {"role": "user", "content": prompt}')
    sections.append("        ]")
    sections.append("    )")
    sections.append("")
    sections.append('    return response.choices[0].message.content')
    sections.append("```\n")
    sections.append("### Configuration Required\n")
    sections.append("```yaml")
    sections.append("# Add to config.yaml:")
    sections.append("llm:")
    sections.append("  enabled: true")
    sections.append("  provider: openai")
    sections.append("  model: gpt-4")
    sections.append("  api_key_env: OPENAI_API_KEY")
    sections.append("```\n")

    # Write report
    report_content = "\n".join(sections)
    Path(output_path).write_text(report_content, encoding="utf-8")